version: "3.8"
services:
  database:
    image: postgres:14.5
    environment:
      POSTGRES_USER: "usr"
      POSTGRES_PASSWORD: "pwd"
      POSTGRES_DB: "telrosdb"
    container_name: postgres
    volumes:
      - ./postgres:/var/lib/postgresql/data
    restart: always

  java-app:
    image: alexdelux/telros:test
    environment:
      SPRING_DATASOURCE_URL: "jdbc:postgresql://database:5432/telrosdb"
    container_name: java-app
    ports:
      - "8080:8080/tcp"
    volumes:
      - ./logs:/etc/java/logs
    restart: always
    depends_on:
      - database

volumes:
  logs:
    driver: local
  postgres:
    driver: local